### ISSUE TITLE
Feature Request: Show all tiles for SuperUser

### ISSUE THREAD

**Issue by WafflesMcDuff** [eosfrontier/PlayerDashboard#2]
SuperUser
GroupID: 8

**Comment by sylcai** [comment]
This should be easy to implement, as the SL group currently also sees all tiles, I expect that this will remain a thing, as the dashboard shouldn't use special Superuser tiles anyway.

This will be implemented soon, but won't be live before F12.

**Comment by sylcai** [comment]
Implemented
